server:
  port: 8000
  timeout: 10s

websocket:
  timeout: 10s
  pong_wait: 30s
  ping_period: 15s

database:
  url: postgres://postgres:pass@localhost:5432/suscord
  log_level: silent

redis:
  addr: localhost:6379
  password: ""
  db: 0

hash:
  salt: cy@$N8f2r\g{3@)rj52

auth:
  secret_key: o!5(U0Ixnln~p9?V|ad(^!J#sygxbECrgHg#K<-

cors:
  origins:
    - "http://localhost:8000"
    - "http://127.0.0.1:8000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
  allowed_headers:
    - "Origin"
    - "Connection"
    - "Content-Type"
    - "Authorization"

media:
  media:
  url: /media
  folder: media
  max_size: 500m
  allowed_media:
    - "video"
    - "image"
    - "audio"

static:
  url: /static
  folder: assets/static
